services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -lc "bundle install && bin/rails db:prepare && bin/dev"
    environment:
      DATABASE_URL: postgresql://bandmgr:bandmgr@db:5432/bandmgr_development
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - ./storage:/app/storage
    tty: true
    stdin_open: true
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bandmgr
      POSTGRES_PASSWORD: bandmgr
      POSTGRES_DB: bandmgr_development
    ports:
      - "5432:5432"
    volumes:
      - bandmgr_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - bandmgr_redis_data:/data

volumes:
  bandmgr_postgres_data:
  bandmgr_redis_data:
  bundle_cache:
