services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -lc "bundle install && bin/rails db:prepare && bin/dev"
    environment:
      DATABASE_URL: postgresql://bandmgr:bandmgr@db:5432/bandmgr_development
      REDIS_URL: redis://redis:6379/1
      MINIO_ROOT_USER: bandmgr
      MINIO_ROOT_PASSWORD: bandmgrpassword
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    tty: true
    stdin_open: true
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bandmgr
      POSTGRES_PASSWORD: bandmgr
      POSTGRES_DB: bandmgr_development
    ports:
      - "5432:5432"
    volumes:
      - bandmgr_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - bandmgr_redis_data:/data
  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: bandmgr
      MINIO_ROOT_PASSWORD: bandmgrpassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - bandmgr_minio_data:/data

volumes:
  bandmgr_postgres_data:
  bandmgr_redis_data:
  bandmgr_minio_data:
  bundle_cache:
