name: bandmgr
description: Open Source Band Manager App
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  drift: ^2.18.0
  path_provider: ^2.1.4
  sqlite3_flutter_libs: ^0.5.24
  collection: ^1.18.0
  csv: ^5.0.2
  uuid: ^4.4.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  drift_dev: ^2.18.0
  lints: ^4.0.0

flutter:
  uses-material-design: true
